//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackTrainDBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public int OriginalPrice { get; set; }
        public int PriceSold { get; set; }
        public int UserSoldTo { get; set; }
        public Nullable<int> TripId { get; set; }
        public int SeatNumber { get; set; }
    
        public virtual Seat Seat { get; set; }
        public virtual Trip Trip { get; set; }
        public virtual User User { get; set; }
    }
}
